# Deployment da aplicação web conversão de peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-peso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-peso
  template:
    metadata:
      labels:
        app: conv-peso
    spec:
      containers:
        - name: conv-peso
          image: jchelp/conversao-peso:v1
          ports:
            - containerPort: 80
          
---
  # Service da aplicação Web conv-peso
apiVersion: v1
kind: Service
metadata:
 name: conv-peso
spec:
 selector:
   app: conv-peso
 ports:
   - port: 80
     targetPort: 80
     nodePort: 30000
 type: LoadBalancer  
